FROM php:8.4-fpm

# Install system dependencies and PHP extensions
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    libzip-dev \
    libonig-dev \
    libpng-dev \
    libxml2-dev \
    libssl-dev \
    zlib1g-dev \
    libicu-dev  \
    && docker-php-ext-install pdo pdo_mysql mbstring bcmath opcache intl zip\
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www


CMD ["php-fpm","-F"]


ARG UID=1000
ARG GID=1000

RUN groupadd -g ${GID} laravel \
 && useradd -u ${UID} -g laravel -m laravel

USER laravel
